version: "3"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=100
    volumes:
      - './config:/config' # Configuration directory
      - '/home/chris/docker/nextcloud/data/__groupfolders/1/Videos:/Video'
      - '/home/chris/docker/nextcloud/data/__groupfolders/1/Music:/Music'
    ports:
      - "8096:8096" # HTTP port
      - "8920:8920" # HTTPS port
    restart: unless-stopped
