version: "3"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=100
    volumes:
      - './config:/config' # Configuration directory
      - './Videos:/Video'
      - './Music:/Music'
    ports:
      - "8096:8096" # HTTP port
      - "8920:8920" # HTTPS port
    restart: unless-stopped
