version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=100
      - FB_BASEURL=/filebrowser
    user: "${UID}:${GID}"
    ports:
      - "8282:8080"
    volumes:
      - './data:/data'
      - './config:/config'    
    restart: unless-stopped
