version: "3"
services:
  icecast:
    container_name: icecast
    image: royvandongen/icecast2-docker:latest
    ports:
      - "4000:8000"
    volumes:
      - './logs:/var/log/icecast2'
      - '/etc/localtime:/etc/localtime:ro'
      - './config/icecast.xml:/etc/icecast2/icecast.xml:ro'
    restart: unless-stopped
