version: "3"
services:
  paste:
    container_name: microbin
    image: danielszabo99/microbin
    restart: unless-stopped
    ports:
     - "8085:8080"
    volumes:
     - ./microbin-data:/usr/local/bin/pasta_data

