## For some reason this container needs to be run with sudo to work properly

version: "3"
services:
  web:
    container_name: web
    image: nginx
    ports:
      - "8989:80"
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    
