version: "3"
services:
  web:
    container_name: web
    image: nginx
    ports:
      - "8989:80"
    environment:
      - NGINX_HOST=pix.carnifex.us
      - NGINX_PORT=80
    volumes:
#      - ./templates:/etc/nginx/templates
      - ./html:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    
