version: "3"
services:
  private-gpt:
    container_name: private-gpt
    image: maadsdocker/tml-privategpt-no-gpu-amd64:latest
    ports:
      - 8001:8001
    environment:
      - net=host
      - GPU=0
      - WEB_CONCURRENCY=1
      - COLLECTION=tml-cisco
    restart: unless-stopped
