version: "3"
services:
  name-of-service:
    container_name: container-name
    image: image/name
    ports:
      - "4443:443/tcp" #server-port:container-port
    environment:
      TZ: 'America/Chicago'
    volumes:
       - './server-folder:/container-folder'
    restart: unless-stopped
