version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer/data:/data
    ports:
      - 9000:9000
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mariadb:
    container_name: mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=H3D2@6JcHkj1MhUQ
      - MYSQL_PASSWORD=H3D2@6JcHkj1MhUQ
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_USER=nextclouduser
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    ports:
      - 40010:80
    links:
      - mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MYSQL_PASSWORD=H3D2@6JcHkj1MhUQ
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_USER=nextclouduser
      - MYSQL_HOST=mariadb
    volumes:
      - ./nextcloud/html:/var/www/html
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
      - ./nextcloud/themes:/var/www/html/themes/
    restart: unless-stopped
  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=100
    volumes:
      - ./emby/config:/config
      - ./share/data/Videos:/Video
      - ./share/data/Music:/Music
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=100
      - FB_BASEURL=/filebrowser
    user: ${UID}:${GID}
    ports:
      - 8282:8080
    volumes:
      - ./share/data:/data
      - ./filebrowser/config:/config
    restart: unless-stopped
  homer:
    image: b4bz/homer
    container_name: homer
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./homer/assets:/www/assets
    ports:
      - 8080:8080
    restart: unless-stopped
  gitea:
    image: gitea/gitea:1.20.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=8hPWo!5m5v!9W&7q
    restart: unless-stopped
    volumes:
      - ./gitea/gitea:/data
      - ./gitea/etc/timezone:/etc/timezone:ro
      - ./gitea/etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 2222:22
    depends_on:
      - db
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=8hPWo!5m5v!9W&7q
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=8hPWo!5m5v!9W&7q
      - MYSQL_DATABASE=gitea
    volumes:
      - ./gitea/mysql:/var/lib/mysql
  paperless-ngx:
    image: lscr.io/linuxserver/paperless-ngx:latest
    container_name: paperless-ngx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - REDIS_URL=
    volumes:
      - ./paperless/config:/config
      - ./paperless/data:/data
    ports:
      - 8000:8000
    restart: unless-stopped
  apache:
    image: httpd:latest
    container_name: apache_1
    ports:
    - 8181:80
    volumes:
    - ./httpd/website:/usr/local/apache2/htdocs
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - PORT_RANGE=30000:30010
    - SUBFOLDER=/
    volumes:
    - ./netboot/config:/config
    - ./netboot/assets:/assets
    ports:
    - 3100:3000
    - 69:69/udp
    - 8585:80
    restart: unless-stopped
volumes:
  mariadb:
